### ISSUE TITLE
Missing Syntax Highlighting

### ISSUE THREAD

**Issue by JAAdrian** [2wayne/MeldPortable#1]
Hi @2wayne ,
thanks for this nice package!

I couldn't get syntax highlighting to work in an ordinary file comparison and was wondering if this could be feasible somehow.

I was testing with two MATLAB files (.m) and C++ files (.cpp) and Meld Portable 3.20 (probably DT1)

**Comment by 2wayne** [comment]
Works for me. Which color scheme are you using?

**Comment by JAAdrian** [comment]
Hi, sorry this is so long gone and I currently don't use Meld Portable. You could think of closing this issue and I suppose that I had a strange system configuration.
